### ISSUE TITLE
[ERROR] Could not pass player interact event.

### ISSUE THREAD

**Issue by empyrean7** [Laurox/VanillaShops#1]
I'm receiving the following error message in the console of my server while running this plugin (currently on Paper MC version 1.15 #29).

27.12 22:16:42 [Server] ERROR Could not pass event PlayerInteractEvent to VanillaShops v0.1
27.12 22:16:42 [Server] INFO java.lang.NullPointerException: null
27.12 22:16:42 [Server] INFO at de.laurox.mc.shops.InteractListener.onItemInteract(InteractListener.java:45) ~[?:?]
27.12 22:16:42 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor62.execute(Unknown Source) ~[?:?]
27.12 22:16:42 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:457) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1373) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
27.12 22:16:43 [Server] ERROR Could not pass event PlayerInteractEvent to VanillaShops v0.1
27.12 22:16:43 [Server] INFO java.lang.NullPointerException: null
27.12 22:16:43 [Server] INFO at de.laurox.mc.shops.InteractListener.onItemInteract(InteractListener.java:45) ~[?:?]
27.12 22:16:43 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor62.execute(Unknown Source) ~[?:?]
27.12 22:16:43 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:457) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1373) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-29]
27.12 22:16:43 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-29]

**Comment by Laurox** [comment]
Can you give further details?

I would be interested if:
- the error occurs on a special action (and if you can describe when exactly)
- did it happen since you installed the plugin or appeared while running it for a while

**Comment by empyrean7** [comment]
I do have Optimized Villagers installed. Could that be altering the AI?

**Comment by Laurox** [comment]
This issue should be fixed in the following update. I will release it soon, stay tuned! 
Thanks a lot for reporting this bug :)
